Разделение версий
QualitySolution/Workwear pull request #106
Opened 2020-10-26 09:03 UTC by DBalt8

Разделение версий: скрытие функции складов

2020-10-26 09:20 UTC, Gankov requested changes

2020-10-26 09:20 UTC, Gankov commented on Workwear/Dialogs/Organization/ObjectDlg.cs
> +			var e = Entity;
Зачем эта строка?

2020-10-26 09:20 UTC, Gankov commented on Workwear/Dialogs/Organization/ObjectDlg.cs
> +		public FeaturesService FeaturesService { get => FeaturesService; private set => featuresService = value; }
Тут можно использовать просто авто свойство, ли не понятно зачем тут публичное свойство вообще, может оно не надо?

2020-10-26 09:20 UTC, Gankov commented on Workwear/MainWindow.cs
> +		var defaultWarehouse = UoW.GetById<Warehouse>(1);
Мы говорил что есть клады, а не то что есть склад с id=1, это разные вещи. никто же не запрещает его удалить...

2020-10-26 09:20 UTC, Gankov commented on Workwear/MainWindow.cs
> +		//if(!(UoW.GetAll<Warehouse>().Count() > 0))
Кстати тут более правильный код. Почему то закомичен.

2020-10-26 09:20 UTC, Gankov commented on Workwear/MainWindow.cs
> +		warehouse.Name = "Default Warehouse";
Почему по английски? Это же пользователь где нибудь сможет увидеть.

2020-10-26 09:20 UTC, Gankov commented on Workwear/MainWindow.cs
> +		page.ViewModel.Filter.Warehouse = new workwear.Repository.Stock.StockRepository().GetDefaultWarehouse(UoW,featuresService);
Вообще не понимаю зачем здесь это?

2020-10-26 09:20 UTC, Gankov commented on Workwear/Repository/Stock/StockRepository.cs
> +				var warehous = uow.GetById<Warehouse>(1);
Первый попавшийся, а не первый по Id

2020-10-26 09:20 UTC, Gankov commented on WorkwearTest/Integration/ReportExportTest.cs
> +using fyiReporting.RdlGtkViewer;
Раньше не работало? Зачем добавлено?

2020-10-26 10:07 UTC, DBalt8 commented on WorkwearTest/Integration/ReportExportTest.cs
> +using fyiReporting.RdlGtkViewer;
Да, почему то у меня без этого не работает

2020-10-27 08:35 UTC, Gankov approved these changes

2020-10-27 08:35 UTC, merged