Правка коллективной выдачи
QualitySolution/Workwear pull request #133
Opened 2021-11-29 07:54 UTC by SpaceTranquility

Внёс правки. Сейчас При выборе сотрудника, выбирается с учётом ранее добавленных строк, сначала довыдаётся одна номенклатура, потом другая и может быть ситуация, когда одному сотруднику выдаётся 2 разные номенклатуры. Я так понял, что сейчас в программе это плохой вариант, т.к. как минимум расчёт довыдачи ломается, когда больше 2 строк с одинаковой нормой. 

Я считаю, что здесь было бы неплохо реализовать выделение цветом, чтобы программа отмечала, сотрудников которым не смогла выдать полностью.

-Можно сделать, чтобы в коллективной выдачи, сначала программа искала нужную номенклатуру в достаточном количестве и если не найдёт выдавала, как сейчас (уменьшит количество ошибок)
-Можно сделать, чтобы искала и выдавала полностью, если не найдёт, то частично, но одной номенклатурой (возможно оптимально, но тут очень желательно цветовое выделение)

2021-11-29 08:30 UTC, Gankov requested changes

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> -		public virtual CollectiveExpenseItem AddItem(EmployeeCard employee, StockPosition position, int amount = 1)
Абсолютно зря убрал возвращение созданного элемента. Даже если это сейчас не где не используется, то точно где нибудь пригодится. Как минимум в тестах, которых возможно пока еще нет для этого документа, что плохо. Потому что вызывая такой метод, ты никогда не узанешь а какая именно строка была добавлена, и не сможешь в ней что-то поменять.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +					int ExpancePositionAmount = 0;  //Осталось на складе с учётом этого документа
В комментарии написано осталось на складе, при этом начинается с 0. И добаляется при проходе документа. Видимо это поле означает что-то другое.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +					foreach(var item in Items) if(item.Nomenclature == position.Nomenclature) ExpancePositionAmount += item.Amount;
Тут будет учтена позиция другого размера. То есть в другой строчке может выдаыаться размер 44 а в этой 45. А тут считается общее количество, одной номеклатуры.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +							AddItem(employeeCardItem, position.StockPosition, NeedPositionAmount); NeedPositionAmount = 0; break;
Чисто стилисчически мне совсем не нравится, когда 3 строка запиханы в одну. Этот код сложнее читается.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +				//if(NeedPositionAmount != 0) Items.Last.Color("orange"); // недовыдоча (нужен ли этот функционал?) И красный если нет совсем
Нужен но не в этом месте. Просто если ты добавишь любую подсветку сюда. то что будет если пользователь поменяет количество? Подсветка не поменяется, допустим в другом месте добавиль код на изменение подсветки. То во первых он будет дублировать это место. Во вторых он должне будет дублировать это вычисление. Так как что мешает пользователю сначала поднять количество до нужно го потом вернутся к не недовыдачи.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> -				newItem = new CollectiveExpenseItem() {
Да здесь похоже был баг.

2021-11-29 08:30 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +		public virtual void AddItem(EmployeeCardItem employeeCardItem, int amount = 1) //Добавляем строку когда нет на складе
Я бы лучше сделал один метод В котором StockPosition position может быть null, чтобы не дублировать методы. Мне кажется код внутри не очень усложнится из за такого решения. Зато сильно упростится любая переработка. Допустим, в строке появилось еще одно поле которое нужно заполнять. А это значит, что нужно будет править и искать уже 2 метода. (Хотя это решение будет тоже не без недостатков, поэтому тут просто в качестве комментария)

2021-11-29 08:44 UTC, SpaceTranquility commented
Ну, я ещё посмотрел. Думаю, надо отменять переход на void и делать выдачу одной позицией. и вносить цвета.
Т.к. текущая правка много ломает и в том числе логику тестов. 
Ревью я сейчас читаю.

2021-12-01 12:00 UTC, Gankov requested changes
Тесты так и поломаны.

2021-12-01 12:01 UTC, Gankov commented on Workwear/Domain/Company/EmployeeCardItem.cs
> +				return ActiveNormItem.Amount - Amount;
Это место так и не вернул назад.

2021-12-10 07:09 UTC, Gankov requested changes

2021-12-10 07:09 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +						if(item.Nomenclature == position.Nomenclature && item.Size == position.Size)
Проверку роста так и не добавил.

2021-12-10 07:09 UTC, Gankov commented on Workwear/Domain/Stock/CollectiveExpense.cs
> +			Items.Remove(item);
Это явно лишее. ObservableItems должен удалить из источника.

2021-12-21 12:24 UTC, Gankov approved these changes

2021-12-21 12:24 UTC, merged