Отметка архивная в номенклатуре
QualitySolution/Workwear pull request #192
Opened 2022-03-04 11:07 UTC by FirstIlyasIT

2022-03-05 08:24 UTC, Gankov requested changes

2022-03-05 08:24 UTC, Gankov commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			if (!baseParameters.CheckBalances) return true;
Ты тут возвращаешь true Хотя по факту никакого сохранения не произошло.
У тебя вообще метод не сохраняет номеклатуру.

2022-03-05 08:24 UTC, Gankov commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			interactiveService.ShowMessage(ImportanceLevel.Error, "Архивная номенклатура не должна иметь остатков на складе");
Для таких целей лучше использовать механизм валидации https://github.com/QualitySolution/QSProjects/wiki/%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F-%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2 А не выводить сообщения в ручную.

2022-03-07 05:40 UTC, FirstIlyasIT commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			interactiveService.ShowMessage(ImportanceLevel.Error, "Архивная номенклатура не должна иметь остатков на складе");
На сколько правильно тащить ОРМ в доменый класс ?

2022-03-09 06:50 UTC, Gankov commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			interactiveService.ShowMessage(ImportanceLevel.Error, "Архивная номенклатура не должна иметь остатков на складе");
Вопрост обсуждаемый, убежден что сейчас у нас не лучшее решение для проброса зависимостей в доменный класс. Вернее я бы сказал у нас вопрос зависимостей доменного класса не решен совсем. Это можно обсдудить. Выбрать какое-то решение, и его придерживаться. Завтра в офисе сможем поднять вопрос.

Но с точки зрения логики, да я на 100% убежден, что данный код проверки должен быть не в диалоге, в классах с бизнес логикой, в нашей текущей архитектуре это доменная модель. Потому что данная проверка должа быть универсальна для любого сохранения объекта, не важно откуда он сохраняется из диалога редактирования или их какого то другого.

2022-03-09 06:54 UTC, FirstIlyasIT commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			interactiveService.ShowMessage(ImportanceLevel.Error, "Архивная номенклатура не должна иметь остатков на складе");
В данном случае, перенёс валидацию в сам класс. Но думаю что в будущем валидацию надо выносить в отдельный класс валидатор. Возможно даже какие-то проверки будут обобщены для всех классов.

2022-03-09 07:00 UTC, Gankov commented on Workwear/Domain/Stock/Nomenclature.cs
> +					var amount = repository.StockBalances(uow, warehouse, nomenclatures, DateTime.Now).FirstOrDefault()?.Amount ?? 0;
Мне кажется в этом месте все таки есть дырка и не однозначность.
Представь ситуациию на складе осталось ботинок 42 размера -5
и 44 размера +10
Первая появится строка с минусом она не подпадет под условие amount > 0 и для этого склада будет считаться что все ок, хотя по факту на нем останется 10 ботинок 44 размера.

2022-03-09 07:02 UTC, Gankov commented on Workwear/ViewModels/Stock/NomenclatureViewModel.cs
> +			interactiveService.ShowMessage(ImportanceLevel.Error, "Архивная номенклатура не должна иметь остатков на складе");
Про обобщение проверок идея интересная.

2022-03-09 07:19 UTC, FirstIlyasIT commented on Workwear/Domain/Stock/Nomenclature.cs
> +					var amount = repository.StockBalances(uow, warehouse, nomenclatures, DateTime.Now).FirstOrDefault()?.Amount ?? 0;
Согласен, исправил

2022-03-09 07:37 UTC, Gankov requested changes

2022-03-09 07:37 UTC, Gankov commented on Workwear/Domain/Stock/Nomenclature.cs
> +						                                  $" склад {warehouse.Name} содержит {Name} в кол-ве {position.Amount} шт.");
Ну и надеюсь уж последнее изменение.
Ты перебираешь несколько позицый на складе, при этом в сообщении это будут одникаковые собщения.
Если останется 5 ботинок 42 и 10 43, пользователь увидит 2 одинкаовых собщения на 5 и на 10.
При этом Name будет один и тот же.

Предлагаю тебе в этом место вместо Name испольвзовать anyBalance.StockPosition.Title Она будет показывать еще и размер если он есть, если нет не будет.

2022-03-09 09:28 UTC, merged