Пока смотреть не надо, для поиска ошибок
QualitySolution/Workwear pull request #205
Opened 2022-04-05 07:40 UTC by FirstIlyasIT

2022-04-07 12:08 UTC, Gankov requested changes
В целом, по ревью. Я немного растроен, потому что. куча изменение которые бестоковые, котороые просто меняют синтаксис чужого кода. Особо ничего не улучшая.
Прошу заметить что я не говорю что весь рефакторинг здесь плохой, куча рефакторга по лямбдам и убирание лишние старые свойства в целом полезна, но к сожалению если огромное количество изменение которые лучше не делают, оставляют читаемость по нулям, со старым вариантом.
А так же есть изменение, которые вредны, например за исключением наверно парочки перевернутых if-ов в конце методов, все остальные былы вредны, потому что нарушают общую логику метода.
И куча изменение которые спорные, в основном это по разбитию на строки, мне лично часто новый вариант меньше нравился. но я понимаю что это вкусовщина так что почти = по нулям, читаемоть.

При этом такой рефаторинг, он имет болшие сайд эффекты:
1 - После этого изменения нам из предыдущих веток будет труднее изменения перетаскивать, так как автоматический мерж уже не проканает. Ибо куча измененых строк. Лишние затраты времени на перенос кода из веток, 2.5, 2.6, 2.7,
2 - Затраты на ревью, а ведь еще предстоит окончательное ревью после починок.
3 - Теперь все разборки а почему так было сделано, дополнительно уложнятся, потому что если смотреть blame то по многим строка последний авто будет Ильяс с его рефакторингам, и чтобы докопаться, а кто же в ориганалет так написал, придется проваливать в глубь изменений и искать изменения до рефакторинга. Это тоже доп время на разборки с кодом, Я часто пытаюсь понять, а зачем это именно так написано, а не иначе.

И при этом, в коде нужно было провести очень много работы, прям реальной работы по перписыванию, сложных вещей (например импорт), где надо было максимально акуратно все предусмотреть чтобы ничего не поломать. И вот здесь, помоему провал. Потому в целом все то сложное, что надо было переделать, по моему либо не заработает как раньше, либо упущены важные детали.

А нам главное чтобы когда мы это все залили в версию ОСМиБТ, они не заметили разницы в работе, кроме того что они могут отключить кучу не используемых у них размеров.

Ильяс я понял что ты хотел как лучше. Думаю на будущее просто надо бы чаще советоваться и чаще задавать вопросы, по ходу дела.

Я возможно в каких коментах, был излишне эмоцеонален, просто потому что много всего у меня вызывало WTF. Ты не обижаяся пожалуйста, я правда многое из токсичных коментов поудалял, но скорей всего часть осталось. Не надо ничего массово откатывать, часть коментов просто нужны для обсуждение,
откатить, переработать стоит:
- 2-х удаленных тестов
- Удаления удаления таблиц массовой выдачи
- функциональность по засериванию уже добавленных в входящий документ рамеров

Все остальное просто приводим в порядок, дорабатываем до рабочего состояния. Тщательно тестим.

2022-04-07 12:13 UTC, Gankov commented on Workwear.Core/Measurements/SizeService.cs
>  	public class SizeService
Но как я увидел позже, тут может быть стоит сделать из этого класса действиетльно сервис. 
Из него убрать запросы в репозиторий. А текущие методы переписать так чтобы он выступал в виде кеша,
То есть он один раз при создании класса загружал все размеры, и дальше уже не дергал. базу. Это очнь надо напрмеро в логике импорта их эксель. Может еще где то такой вариант работы будет полезен. То есть правильнее считаю разделить. В тех местах где обащательно нужна последняя инфа из базы использовать репозиторий. А в остальном этот класс сервиса.

2022-04-07 12:22 UTC, Gankov commented on Workwear/Domain/Company/EmployeeCard.cs
> +			=> observableSizes ?? (observableSizes = new GenericObservableList<EmployeeSize>(Sizes));
Это вместо лайка, чтобы не подумал инчего плохого...

2022-04-07 12:43 UTC, Gankov commented on Workwear/Domain/Stock/ItemsType.cs
> -		public virtual СlothesType? WearCategory {
Если мы не запилим в 2.7 каталог с типами номенклатуры, то это поле надо будет возвращать.

2022-04-07 12:57 UTC, Gankov commented on Workwear/Views/Stock/ExpenseDocItemEmployeeView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(viewModel.expenseEmployeeViewModel.UoW, x.Nomenclature?.Type?.SizeType))
Это надо исправлять везде, я не стал про каждое такое место писать.

2022-04-08 07:49 UTC, FirstIlyasIT commented on Workwear.Core/Measurements/SizeService.cs
> +			bool unusedInEmployee = false)
Согласен, название подобрано не очень хорошее, попробую придумать что-то более подходящее под логику метода

2022-04-08 07:57 UTC, FirstIlyasIT commented on Workwear/Domain/Company/EmployeeCardItem.cs
> +				logger.Warn("В карточке сотрудника не указан рост");
Я думаю, что несколько ростов не должно быть проблемой

2022-04-08 08:25 UTC, Gankov commented on Workwear.Core/Measurements/SizeService.cs
> +			bool unusedInEmployee = false)
Может заменить на Enum? или на отдельные методы как было в старом сервисе.
Потому что по моей логине не нужны все возможные комбинации...
По сути из того что я вижу на нужны 2 основыные комбинации.
1 - Размеры которые можно использовать в сотруднике
2 - Размеры которые можно использовать в номеклатруе.

И возможно где то понядобится 3-я, но я не уверне где она нужна. А именно просто все размеры..

2022-04-08 08:28 UTC, Gankov commented on Workwear/Domain/Company/EmployeeCardItem.cs
> +				logger.Warn("В карточке сотрудника не указан рост");
В данном случае я имел виду другое.
Представь, у нас есть стандартный рост. Пользователь зачем то создает второй вариант ростов.
В номеклатуре указывает новый вариант, свой собственный.
И программа ругается говорит "В карточке сотрудника не указан рост", пользователь лезет в сотрудника смотрит, а в нем рост указан, но стандартный, а не тот на который ругается программа. Пользователь в конфузе.

2022-04-08 09:39 UTC, Gankov requested changes

2022-04-08 09:39 UTC, Gankov commented on Workwear/ViewModels/Stock/SizeTypeViewModel.cs
> +				isStandartSize = true;
Мне кажется тут не правильно. Если размер новый, то как он может быть стандартным?

2022-04-08 09:39 UTC, Gankov commented on Workwear/ViewModels/Stock/SizeTypeViewModel.cs
> +		public bool CanEdit => !IsNew && !isStandartSize;
И тут. Правльно я ли я понимаю что новый тип размера нельзя редактировать?

2022-04-08 09:39 UTC, Gankov commented on Workwear/Views/Stock/SizeTypeView.cs
> +				.AddBinding(ViewModel, vm => vm.IsNew, v => v.Sensitive)
Мне кажется что категорию можно менять только при создании. Когда уже добавлены размеры, мне кажется категорию надо запретить менять, иначе будет бардак если кто-то поменят категорию посте того как размеры уже разошлись по базе и были добавлены складской учет.

2022-04-08 09:39 UTC, Gankov commented on Workwear/Views/Stock/SizeTypeView.cs
> +			ybuttonRemoveSize.Sensitive = sizeId >= 1000;
В идеале 1000 вынести в какое то статическое поле, лучше даже в viewModel.
Вообще в целом, если какое-то значение в программе используется в нескольких местах, и должно менятся сихнонно как здесь, лучше выносить хранение значения в одно место.

Допустим в друг решили что 1000 не хватает и надо больше. Если руками искать все места, то можно где то пропустить.

2022-04-08 09:39 UTC, Gankov commented on Workwear/Views/Stock/SizeView.cs
> +				.AddBinding(ViewModel, vm => vm.CanEdit, v => v.Sensitive)
Тут я тоже думаю что у размера, тип менять нельзя, после того как он сохранен.
А может стоит вообще убрать его из диалога.

2022-04-08 09:41 UTC, Gankov submitted a review, later dismissed

2022-04-08 13:12 UTC, FirstIlyasIT commented on Workwear/Views/Stock/Widgets/SizeWidgetView.cs
> -		private void ExcludeExistingSizes()
При добавлении существующего размера его кол-во увеличивается, думаю так правильней чем было сделано. Но если принципиально верну назад.

2022-04-08 13:20 UTC, Gankov requested changes

2022-04-08 13:20 UTC, Gankov commented on Workwear/Dialogs/Stock/WriteOffItemsView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType))
Мне кажется здесь надо onlyUseInNomenclature:true

2022-04-08 13:20 UTC, Gankov commented on Workwear/Views/Statements/IssuanceSheetView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(ViewModel.UoW, x.Nomenclature?.Type?.SizeType, true, true))
Мне кажется оба true в этом методе почти всегда будут ошибкой, мне трудно предстваить надо пересечение.
Здесь onlyUseInNomenclature:true

2022-04-08 13:20 UTC, Gankov commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> +						SizeService.GetSize(viewModel.сollectiveExpenseViewModel.UoW, x.Nomenclature?.Type?.SizeType, true, true))
Здесь onlyUseInNomenclature:true

2022-04-08 13:20 UTC, Gankov commented on Workwear/Views/Stock/ExpenseDocItemEmployeeView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(viewModel.expenseEmployeeViewModel.UoW, x.Nomenclature?.Type?.SizeType, true, true))
Здесь onlyUseInNomenclature:true

2022-04-08 13:20 UTC, Gankov commented on Workwear/Views/Stock/SizeTypeView.cs
> +					String.Join(" ,", x.SuitableSizes.Select(z => z.Name)))
Может лучше ", ", сначала запятая потом пробел.

2022-04-08 13:20 UTC, Gankov commented on Workwear/Views/Stock/IssueByIdentifierView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(ViewModel.UowOfDialog, x.Nomenclature.Type.SizeType,true, true))
Здесь onlyUseInNomenclature:true

2022-04-08 14:33 UTC, Gankov requested changes

2022-04-08 14:33 UTC, Gankov commented on Workwear/Dialogs/Stock/WriteOffItemsView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, true))
Блин, ну почему ты не хочешь здесь использовать именованые параметры
Если бы написал вот так `SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, onlyUseInNomenclature:true)`
Не было бы ошибки, было бы сразу видно что означает true, без влезания внутр. Видишь как правино написанный код влияет на читаемость, и исключает случайные ошибки.
Во всех складских документах дожны быть использованы только размеры доступные для номенклатуры а не для сотрудника.

2022-04-08 14:33 UTC, Gankov commented on Workwear/Views/Statements/IssuanceSheetView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(ViewModel.UoW, x.Nomenclature?.Type?.SizeType, true))
И опять, здесь только в номеклтаруте. Сделай `SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, onlyUseInNomenclature:true)` Не будет таких ошибок.

2022-04-08 14:33 UTC, Gankov commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> -						SizeService.GetSize(viewModel.сollectiveExpenseViewModel.UoW, x.Nomenclature?.Type?.SizeType, true, true))
SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, onlyUseInNomenclature:true)

2022-04-08 14:33 UTC, Gankov commented on Workwear/Views/Stock/ExpenseDocItemEmployeeView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(viewModel.expenseEmployeeViewModel.UoW, x.Nomenclature?.Type?.SizeType, true))
SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, onlyUseInNomenclature:true)

2022-04-08 14:33 UTC, Gankov commented on Workwear/Views/Stock/IssueByIdentifierView.cs
> +					.DynamicFillListFunc(x => SizeService.GetSize(ViewModel.UowOfDialog, x.Nomenclature.Type.SizeType,true))
SizeService.GetSize(UoW, x.Nomenclature?.Type?.SizeType, onlyUseInNomenclature:true)

2022-04-11 07:53 UTC, Gankov commented on Workwear.Core/Measurements/SizeService.cs
> +				types = types.Where(x => x.UseInEmployee);
Смотри тут баг.
Ты в types используешь как кеш. То есть в сллеюущие раз ты не будет получать из базы значение...
При этот здесь ты в types кладешь значение отфильтрованное по UseInEmployee, при втором заходе в метод, с отключенным onlyUseInEmployee значение все равно будет уже без неиспользуемых в сотруднике.
А если onlyUseInEmployee, то по верх будет еще один фильтр, и так далее. фильты будут множится... Что будет каждый раз увеличивать скорость обработки последовательности.

2022-04-11 07:53 UTC, Gankov commented on Workwear.Core/Measurements/SizeService.cs
> +				types = types.Where(x => x.UseInEmployee);
+ хранить лучше не IEnumerable, а List или что-то такое, почему то IDE ругаются когда приосходит повторный перебор, типа это плохо. Я не знаю почему.

2022-04-11 08:19 UTC, FirstIlyasIT commented on Workwear.Core/Measurements/SizeService.cs
> +				types = types.Where(x => x.UseInEmployee);
В какой момент ругается? Из-за того что-то lazy без листа ?

2022-04-11 08:52 UTC, Gankov commented on Workwear.Core/Measurements/SizeService.cs
> +				types = types.Where(x => x.UseInEmployee);
В этом месте не ругается, ибо здесь она не может понять что есть несколько переборов. Но в любом втором переборе IEnumerable ide пишет что не надо так делать. Если в одном методе явно IEnumerable будет перебираться несолько раз, то она об этом напишет. мне писала. 

Я правда не знаю почему это полохо.
И нет Лейзи тут не причем, это про любой перебор IEnumerable.

2022-04-11 09:00 UTC, Gankov commented on Workwear.Core/Repository/Sizes/SizeRepository.cs
> +            uow.Session.QueryOver<Size>().List().ToList();
Зазве в этом месте уже не создается IList? Зачем второй раз ToList.
И вооеще как то в этом комите слишком много лишних ToList. Но бог сним поехали дальше.

2022-04-13 06:32 UTC, Gankov commented on Workwear/Domain/Stock/CompletionItem.cs
> +            get => WarehouseOperation.WearSize;
Проверял точно при таком решении не будет падать создании новой строки?
Может быть стоит тогда сразу создавать и объект операции? Чуть выше?

2022-04-13 06:32 UTC, Gankov commented on Workwear/HibernateMapping/Stock/CompletionResultItemMap.cs
> -            References(x => x.Height).Column("height_id");
Не забудь тогда удалить колонки из базы.

2022-04-19 11:45 UTC, FirstIlyasIT commented on Workwear/Domain/Stock/CompletionItem.cs
> +            get => WarehouseOperation.WearSize;
Если добавлять новые позиции через метод additem, то создаётся и новый складской документ

2022-04-19 11:46 UTC, FirstIlyasIT commented on Workwear/HibernateMapping/Stock/CompletionResultItemMap.cs
> -            References(x => x.Height).Column("height_id");
Её там и не было, раньше также через операцию прокидывали. Это я когда делал натупил

2022-04-19 13:12 UTC, FirstIlyasIT commented on Workwear/Repository/Stock/StockRepository.cs
> +			   .SelectGroup(() => warehouseOperationAlias.WearSize).WithAlias(() => resultAlias.WearSize)
Да, во всех диалогах где это вызывается нормально передаётся размер и рост

2022-04-19 13:15 UTC, FirstIlyasIT commented on Workwear/Repository/Stock/StockRepository.cs
> -				&& (warehouseIncomeOperationAlias.Size == warehouseOperationAlias.Size
По крайне мере, все тесты которые считаю остатки на складе не упали

2022-04-22 09:05 UTC, Gankov requested changes

2022-04-22 09:05 UTC, Gankov commented on Workwear/gtk-gui/workwear.Journal.Filter.Views.Stock.SizeFilterView.cs
> +
Забыл удалить этот файл когда переносил в другую папку. Это дубль.

2022-04-22 10:36 UTC, Gankov approved these changes

2022-04-22 10:36 UTC, merged