Убрал зависимость
QualitySolution/Workwear pull request #211
Opened 2022-04-26 14:07 UTC by FirstIlyasIT

2022-04-26 14:20 UTC, Gankov requested changes

2022-04-26 14:20 UTC, Gankov commented on Workwear/Dialogs/Organization/EmployeeVacationDlg.cs
> +			foreach(var item in yentryVacationType.ItemsList) {
Зачем здесь пустой цикл?

2022-04-26 14:20 UTC, Gankov commented on Workwear/gtk-gui/workwear.Views.Regulations.NormView.cs
> +		private global::Gamma.GtkWidgets.yButton buttonShowHistory;
Возможно это из другой задачи?

2022-04-26 14:20 UTC, Gankov commented on Workwear/gtk-gui/workwear.Views.Regulations.NormView.cs
> -			this.yentryRegulationDoc.Changed += new global::System.EventHandler(this.OnYentryRegulationDocChanged);
Теперь обработки зименения документ не будет. Либо нужно удалить сам метод, либо поправить заполнение приложений....

2022-04-26 14:39 UTC, FirstIlyasIT commented on Workwear/gtk-gui/workwear.Views.Regulations.NormView.cs
> +		private global::Gamma.GtkWidgets.yButton buttonShowHistory;
Нет, это сама так пересобралась gtk

2022-04-26 14:46 UTC, FirstIlyasIT commented on Workwear/gtk-gui/workwear.Views.Regulations.NormView.cs
> +		private global::Gamma.GtkWidgets.yButton buttonShowHistory;
Кнопка есть, а действий к ней не привязано

2022-04-27 07:15 UTC, Gankov approved these changes

2022-04-27 07:16 UTC, merged