Детализация вывода теста сравнения обновлённой базы с чисто созданой.
QualitySolution/Workwear pull request #287
Opened 2023-01-17 15:20 UTC by SpaceTranquility

Старый не удалял

2023-01-17 16:07 UTC, Gankov requested changes
Твой код не проверяет ситуации если в базе 2 присутствует колонка но при этом отсутствует в базе 1. Правильно я понимаю? Хотя мы это обсуждали. И я несколько раз говорил что циклов будет 2 в обе стороны.

Второе мы договаривались что ты будешь проверять не только колонки но и индексы и внешние ключи. Внешние ключи это капец как важно. Индексы менее но все равно. Желательно чтобы имена у них не различались. Этого вообще не вижу.

2023-01-18 07:49 UTC, SpaceTranquility commented
Добавлю

2023-01-18 13:35 UTC, SpaceTranquility commented
Блин, ещё косяк увидел после прогонки.

2023-01-18 13:48 UTC, SpaceTranquility commented
Исправил.

2023-01-19 10:32 UTC, Gankov approved these changes

2023-01-19 10:32 UTC, merged