Возможность индивидуальной выдачи в коллективной.
QualitySolution/Workwear pull request #291
Opened 2023-02-06 07:44 UTC by SpaceTranquility

Добавил виджет позволяющий массово выдавать как коллективные, так и индивидуальные позиции. Пересмотрел некоторые кнопки, дополнил контекстное меню заменой. Добавил возможность добавить подразделением. Надеюсь для пользователей это не будут слишком множественные и неочевидные изменения.

2023-02-06 07:47 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +				if(onlyCollectiveIissueType && item.ProtectionTools?.Type.IssueType != IssueType.Collective)
Может стоит добавить тип IssueType.Any?

2023-02-06 07:51 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +		public class IssueWigetArgs : EventArgs {
Пока не понял что оптимальнее: передавать результат через событие gtk или как сейчас редактируя передаваемый виджету справочник напрямую.

2023-02-06 07:52 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +		public IssueWidgetViewModel(INavigationManager navigation, Dictionary<int,IssueWidgetItem> wigetItems) : base(navigation) {
Хотел поставить словарю ref, но как я понял этот конструктор используется не совсем по прямому назначению.

2023-02-07 05:39 UTC, Gankov commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +				if(onlyCollectiveIissueType && item.ProtectionTools?.Type.IssueType != IssueType.Collective)
Думаю пока не стоит. Ибо это было простое решение. Сейчас когда сделали полное решение, в таком тип практически нет смысла.

2023-02-07 05:57 UTC, Gankov commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +		public IssueWidgetViewModel(INavigationManager navigation, Dictionary<int,IssueWidgetItem> wigetItems) : base(navigation) {
Именно по прямому назначению. Я если честно даже и не знал, что в конструктор можно ref добавлять. Ну если можно, как то сходу кажется что это порочная практика. То есть фактически она обязывает весь класс быть временным сиюминутным. То есть создал, надо что-то сделать внутри метода и убить класс, завершил метод. У нас везде код построен по принципу отдал и забыл. А вернуть должны результат. А это в большинстве случаев должно быть что-то новое. Ну мне просто кажется, так проще выстраивать логику. Меньше неожиданностей может происходить. Ибо я везде работая в нутри класса не должен думать что я вот сейчас здесь что-то лишнее поменяю, а кто-то с наружи упадет, потому что оказывается он мне передал объект не на всегда. Ну не знаю, может есть ситуации где реф оправдан, но сходу кажется нет.

2023-02-07 10:45 UTC, Gankov requested changes

2023-02-07 10:45 UTC, Gankov commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +				if(!wigetItems.First(x => x.Key == itemsList[i].ProtectionTools.Id)
Сложно. как-то. Ну во первых у тебя словарь. Наличие ключа можно проверять по ContainKey и это будет для словаря работать быстро а твой перебор элементов медленно.
Ну и вообще мне было бы понятнее
itemsList = itemsList.Where(x => wigetItems.ContainKey(x.ProtectionTools.Id) && x[x.ProtectionTools.Id]).ToList()
Чем пробиратся через дебри кода перебирающего колекцию задом наперед и удаляющее ее элементы.

И кстати ты уверен что этот лист, который передали тебе в функцию с наружи никогда не используется. Чтобы удалять из него элементы? Или так и задумано? И надо действительно удалять и я не вижу связаной логики в других элементах.

2023-02-07 10:45 UTC, Gankov commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +		public void Refresh(CollectiveExpenseItem[] selectedCollectiveExpenseItem = null) {
Мы это обсуждали, мне кажется 2-я методами понятнее.

2023-02-07 10:45 UTC, Gankov commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +	private ProtectionTools protectionTools;
Можно было использовать авто свойство для всех свойств ниже. Меньше кода, меньше багов!

2023-02-07 10:45 UTC, Gankov commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> -			buttonAdd.Binding.AddBinding(ViewModel, v => v.SensetiveAddButton, w => w.Sensitive).InitializeFromSource();
При удалении строки не чего не смутило?
SensetiveAddButton больше не нужен? если не нужен надо было его удалить.
А может быть стоило подумать, может он для чего то был нужен. И этот функционал все таки надо реализовать.

Ты пойми для меня на ревью упустить такие моменты очень просто, я не могу видя изменения кода в гитхабе, настолько в голове все замечать и проигрывать. Ты как програмист, долнен в первую очедедь такие штуки отслеживать. Лично мне в тот момент когда я удаляю что-то мне просто подумать о том что может быть тут было что-то важное. А так на ревью заметить сложно. Будем пропускать много багов в релиз, когда раньше что-то работало, а после внесения изменений перестало.

2023-02-07 10:45 UTC, Gankov commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> +			item.Activated += (sender, e) => ViewModel.Refresh(ytreeItems.GetSelectedObjects<CollectiveExpenseItem>());
А если никакая строка не выбрана? Здесь упадем. Надо серить пункт меню.

2023-02-07 10:45 UTC, Gankov commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> -			buttonDel.Sensitive = buttonShowAllSize.Sensitive = buttonRefreshEmployee.Sensitive = ytreeItems.Selection.CountSelectedRows() > 0;
Кстати и вот здесь код устанавливающий buttonShowAllSize.Sensitive для старой кнопки удален. А у новой это не реализовано. Я не нашел?

2023-02-07 10:45 UTC, Gankov commented on Workwear/Views/Stock/Widgets/IssueWidgetView.cs
> +			var label5 = new Label {LabelProp = "Штук"};
Ужасное название. А если там будут ботинки?
Тоже штук? Или все таки пар?

2023-02-07 10:45 UTC, Gankov commented on Workwear/gtk-gui/Workwear.Views.Stock.CollectiveExpenseItemsView.cs
> +			this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString("Дополнить");
По поводу этого лейбла, может с Любой посоветуемся. ХЗ, не нравится название. НО прям правильного варианта пока придумать не могу.

2023-02-07 10:45 UTC, Gankov commented on Workwear/gtk-gui/Workwear.Views.Stock.CollectiveExpenseItemsView.cs
> -			this.buttonShowAllSize.Label = global::Mono.Unix.Catalog.GetString("Выбрать другой размер");
Ты кнопку другие размеры удали? Блин мы не про это говорили. Мы похоже перепутал 2 разные задачи, мы говорили про замену протекшен тулс в документе выдачи. и там это хотели прятать в меню потому что это редкий функционал, не надо чтобы им пользовались часто.
А эта кнопка очень нужна! Ей часто люди пользоваться будут и должны ее не надо прятать, ее надо показать было. Она даже больше нужна чем перезаполнить. Вот перезаполнить и документ и сотрудника, вот это можно было спрятать.

2023-02-07 10:45 UTC, Gankov commented on Workwear/gtk-gui/Workwear.Views.Stock.Widgets.IssueWidgetViewModel.cs
> +namespace  eear.Views.Stock.Widgets
Че за нафиг, зачем этот файл в гите? Еще раз прошу проверяй прям каждую строчку которую комитишь.
Тебя правда ничего не смутилов в этой строке? Что это за неймспейс такой? Или ты все таки не проверяешь тот код который комитиш. Ну пожалуйста. Очень прошу. Ну почему я на верью должен проверять всякий мусор, ты представляешь сколько я времени трачу на ревью. И если там куча мусора? Ну не ужели в момент комита не проверить первоначально все что комитишь самому. Чтобы не грузить других.

2023-02-07 10:52 UTC, Gankov commented
Дополнительно добавляет уволенных.
Еще если никого не добавляет, то зачем то показывает пустой виджет. Это как то тупо. Тоже происходит если уже все добавили. Тут кстати лучше бы выводить сообщение, а не просто не показывать виджет, ибо будет не понятно почему нельзя обновить сотрудника.

2023-02-07 15:41 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +		public IssueWidgetViewModel(INavigationManager navigation, Dictionary<int,IssueWidgetItem> wigetItems) : base(navigation) {
+

2023-02-07 15:41 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +		public class IssueWigetArgs : EventArgs {
+

2023-02-07 15:48 UTC, SpaceTranquility commented on Workwear/Views/Stock/Widgets/IssueWidgetView.cs
> +			var label5 = new Label {LabelProp = "Штук"};
"Кол-во"

2023-02-07 15:52 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +				if(onlyCollectiveIissueType && item.ProtectionTools?.Type.IssueType != IssueType.Collective)
+

2023-02-07 16:00 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +		public virtual void AddEmproees(List<EmployeeCard> employees, BaseParameters baseParameters, bool onlyCollectiveIissueType = true) {
Ну, он уже не используется. Сейчас это вьюмодель делает. Хотя я не уверен, что это не должен делать сам документ, по крайней мере уметь. Хотя, если оставлять, то подержиать будет не очень.

2023-02-08 06:44 UTC, Gankov commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +		public virtual void AddEmproees(List<EmployeeCard> employees, BaseParameters baseParameters, bool onlyCollectiveIissueType = true) {
Решил оставить метод? Я бы удалил. Раз он сразу не используется то и потом не понадобится.

2023-02-08 07:17 UTC, Gankov commented on Workwear/Views/Stock/Widgets/IssueWidgetView.cs
> +			var label5 = new Label {LabelProp = "Штук"};
Можно и полностью "Количество" Чего там экранное место экономить.

2023-02-08 07:19 UTC, Gankov commented on Workwear/gtk-gui/Workwear.Views.Stock.CollectiveExpenseItemsView.cs
> +			this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString("Дополнить");
Ну хотя сейчас подумал, так как сейчас это работает. "Дополнить" наверное лучший вариант. Я просто все еще по старому думаю.

2023-02-09 16:57 UTC, SpaceTranquility commented on Workwear/Views/Stock/Widgets/IssueWidgetView.cs
> +			var label5 = new Label {LabelProp = "Штук"};
Под столбик в 2 символа слишком широко. Я вообще хотел "штук" или перевернуть на 90 некоторые. Но это тоже убого смотрится.

2023-02-09 16:59 UTC, SpaceTranquility commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> -			buttonDel.Sensitive = buttonShowAllSize.Sensitive = buttonRefreshEmployee.Sensitive = ytreeItems.Selection.CountSelectedRows() > 0;
+

2023-02-09 18:30 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +					if (position.Amount - AmountInList(position.StockPosition,addedItems) - AmountInList(position.StockPosition, Items) >= needPositionAmount && position.WearPercent == 0) //Частичных выдач не деела
Когда в прошлый раз делали, решили делать без частичных выдач. Либо полную одной строкой, либо редачить вручную. Единственное, сейчас нет возможности строку добавить вручную.

2023-02-10 07:40 UTC, Gankov commented on Workwear/Views/Stock/Widgets/IssueWidgetView.cs
> +			var label5 = new Label {LabelProp = "Штук"};
Нормально.

2023-02-10 11:46 UTC, SpaceTranquility commented on Workwear/gtk-gui/Workwear.Views.Stock.CollectiveExpenseItemsView.cs
> -			this.buttonShowAllSize.Label = global::Mono.Unix.Catalog.GetString("Выбрать другой размер");
Теперь есть кнопка "заменить", это лучший вариант, который я придумал, но я не помню на каком мы сошлись. Можно переименовать.

2023-02-13 06:39 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpenseItem.cs
> +			result.employeeIssueOperation = employeeIssueOperation;
Удалил

2023-02-13 06:42 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +		public virtual void AddEmproees(List<EmployeeCard> employees, BaseParameters baseParameters, bool onlyCollectiveIissueType = true) {
Удалил. Теперь только во вьюмодели.

2023-02-13 06:43 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +		public virtual CollectiveExpenseItem PickItem(EmployeeCardItem employeeCardItem, List<CollectiveExpenseItem> addedItems, BaseParameters baseParameters)
Это был список "добавляемых элементов" с которым работал виджет и подсчёт amount при том подходе его активно использовал.

2023-02-13 06:48 UTC, SpaceTranquility commented on Workwear.Desktop/Domain/Stock.Documents/CollectiveExpense.cs
> +					if (position.Amount - AmountInList(position.StockPosition,addedItems) - AmountInList(position.StockPosition, Items) >= needPositionAmount && position.WearPercent == 0) //Частичных выдач не деела
Сейчас не считает. Проставляет потребность полностью, если она есть и есть на складе; 0 если есть на складе, выбрана для добавления, но нет потребности; если есть потребность, выбрана, но нет подходящего на складе - добавит строку, без номенклатуры, чтобы подсветилась красным.

2023-02-13 06:48 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +			savedItems = new List<CollectiveExpenseItem>();
Ушёл

2023-02-13 06:50 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
>  				progress.Add();
Исправил.

2023-02-13 06:53 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +			page.ViewModel.AddItems += () => AddItemsAdvanced(itemsList, wigetList, page);
Поменял

2023-02-13 06:59 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +				if(!wigetItems.First(x => x.Key == itemsList[i].ProtectionTools.Id)
Здесь логику уже изменили.

2023-02-13 07:01 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +				.Where(x => x.Subdivision.Id.IsIn(subdivizionIds))
Учёл.

2023-02-13 07:03 UTC, SpaceTranquility commented on Workwear/ViewModels/Stock/CollectiveExpenseItemsViewModel.cs
> +		public void Refresh(CollectiveExpenseItem[] selectedCollectiveExpenseItem = null) {
В целом, согласен. Разделил.

2023-02-13 07:03 UTC, SpaceTranquility commented on Workwear/Views/Stock/CollectiveExpenseItemsView.cs
> +			item.Activated += (sender, e) => ViewModel.Refresh(ytreeItems.GetSelectedObjects<CollectiveExpenseItem>());
Видимости исправил

2023-02-13 10:21 UTC, Gankov requested changes

2023-02-13 10:21 UTC, Gankov commented on Workwear/ViewModels/Stock/Widgets/IssueWidgetViewModel.cs
> +	private int numberOfNeeds;
Здесь та строка ненужна, так как реализовано авто свойство. Кстати я даже не знаю подхватит ли автосвойство это поле. Ибо возможно здесь баг. В конструкторе ты кладешь в внутреннее поле, а снаружи наверняка авто свойством пользуешься.

2023-02-13 10:21 UTC, Gankov commented on Workwear/gtk-gui/Workwear.Views.Stock.Widgets.IssueWidgetViewModel.cs
> +namespace  eear.Views.Stock.Widgets
А почему диалог помечен как решенных, хотя этот файл из гита не пропал.

2023-02-13 13:34 UTC, Gankov approved these changes

2023-02-13 13:37 UTC, merged