Добавил проверку отпусков
QualitySolution/Workwear pull request #299
Opened 2023-03-07 11:02 UTC by SpaceTranquility

2023-03-07 11:50 UTC, Gankov approved these changes

2023-03-07 11:50 UTC, Gankov commented on Workwear.Desktop/Domain/Company/EmployeeCard.cs
> +				if(vacation.BeginDate <= date && vacation.EndDate > date)
Я бы тогда сделал  vacation.EndDate.AddDay(1) > date
Просто скорей всего под отпуском понимают что последняя дата включительно.

2023-03-07 14:18 UTC, SpaceTranquility reviewed
Только меня смущает, что пользователь может дату поменять или удалить. Хотя программа и не падает с пустой датой. Может туда валидатор добавить?

2023-03-07 14:25 UTC, SpaceTranquility commented
И что bestChoise первым выдаёт позиции с износом. 
А так как мы не учитываем сами добавляемые позиции, то эта изношенная просто проставится всем.
А документ при сохранении не ругается и в результате выдаёт n изношенных позиций, которая ччаще всего 1 
В результатае на складе минус изношенные позиции.

Это тоже надо подумать и исправить. Как минимум сохранение, чтобы она такое не позволяла, и неплохо бы в коллективной изношенное не выдавать.

2023-03-07 14:44 UTC, Gankov approved these changes

2023-03-07 14:45 UTC, Gankov approved these changes

2023-03-07 14:46 UTC, Gankov commented
> Только меня смущает, что пользователь может дату поменять или удалить. Хотя программа и не падает с пустой датой. Может туда валидатор добавить?

Здесь думаю не надо ничего. Ну поменяет и поменяет. В документ да если вдруг можно сохранить его без даты. надо добавить проверку.

2023-03-07 14:49 UTC, Gankov commented
> И что bestChoise первым выдаёт позиции с износом. А так как мы не учитываем сами добавляемые позиции, то эта изношенная просто проставится всем. А документ при сохранении не ругается и в результате выдаёт n изношенных позиций, которая ччаще всего 1 В результатае на складе минус изношенные позиции.
> 
Ну во первых насколько я помню изношеныне наоборт последними должны выдаваться.

Во вторых, как это не проверяет. проверяет количество на складе, если не отключена эта настройка.

> Это тоже надо подумать и исправить. Как минимум сохранение, чтобы она такое не позволяла, и неплохо бы в коллективной изношенное не выдавать.
Да откуда такое стремление все запретить. наоброт. чем больше возможностей тем лучше.

2023-03-07 14:51 UTC, Gankov requested changes
Куча тестов поломана исправля!

2023-03-09 06:10 UTC, SpaceTranquility commented
> Куча тестов поломана исправля!

2023-03-09 06:15 UTC, SpaceTranquility commented
А "операция выдачи сотруднику" без сотрудника корректна?
Или лучше добавить в метод(ы) эксепшен, а в тесты добавить к операции сотрудника?

2023-03-09 14:27 UTC, SpaceTranquility commented
Сделал  в тестах заглушку. убрал проверку из метода. Думаю, она там только баги будет делать.

2023-03-10 06:08 UTC, Gankov approved these changes

2023-03-10 06:08 UTC, merged