Списание ручных операций.
QualitySolution/Workwear pull request #328
Opened 2023-06-15 11:58 UTC by SpaceTranquility

2023-06-15 12:06 UTC, Gankov commented on Workwear/Journal/ViewModels/Company/EmployeeBalanceJournalViewModel.cs
> +	    public string ItemName => ManualOperation ? ProtectionToolsName : NomenclatureName;
Считаю что здесь сделано не универсально. Зачем ты привязываешься к ручной операции?
Ты в этом месте зашиваешь такую логику. "ручные операции всегда без номенклатуры".
Но фишка в том что это только пока. Я вообще хотел, сделать изначально просто возможность указывать в ручных операциях номенклатуру, когда Ольга проблему озвучила, чтобы ее можно было возвращать на склад. Но пока временно отказались от этой идеи. Чтобы сделать быстрее. (а вот быстрее и не получилось походу). это временно, завтра наверно придется сделать чтобы можно было все остальное тоже заполнять, номенлатуру, размеры т.п. в ручные тоже. А ты тут зачем то рассчитываешь на то что ручные операции всегда будут без номенклатуры.

Хотя в твоем случае логика то другая. Если нет номенклатуры, показывай номенклатуру нормы. Ты же это хотел? Ну так напрямую это и нужно было реализовывать. А не переусложнять.

2023-06-15 12:07 UTC, Gankov commented on Workwear/Journal/ViewModels/Company/EmployeeBalanceJournalViewModel.cs
> +	    public string BalanceText => $"{Balance} {UnitsName}"; //Пока не уверен, стоит ли единицу измерения получать для ручной операции
Единицу измерения в данном случае нужно тянуть из типа номенклатуры нормы, вот и все.

2023-06-15 12:31 UTC, SpaceTranquility commented on Workwear/Journal/ViewModels/Company/EmployeeBalanceJournalViewModel.cs
> +	    public string ItemName => ManualOperation ? ProtectionToolsName : NomenclatureName;
Да, согласен. Поменяю. А как ты относишсь к добавлению номенклатуры нормы во вью самого журнала? Может быть полезно знать по какой потребности выдано или это очевидно?

2023-06-15 13:40 UTC, SpaceTranquility commented on Workwear/Journal/ViewModels/Company/EmployeeBalanceJournalViewModel.cs
> +	    public string BalanceText => $"{Balance} {UnitsName}"; //Пока не уверен, стоит ли единицу измерения получать для ручной операции
Это понятно. Просто не захотел сразу ещё по 4 джоина и селекта добавлять, поэтому и коммент повсил.

2023-06-16 06:11 UTC, Gankov commented on Workwear/Journal/ViewModels/Company/EmployeeBalanceJournalViewModel.cs
> +	    public string ItemName => ManualOperation ? ProtectionToolsName : NomenclatureName;
Нормально отношусь, если места хватит.

2023-06-19 10:59 UTC, Gankov requested changes

2023-06-19 10:59 UTC, Gankov commented on Workwear.Desktop/Domain/Stock.Documents/IncomeItem.cs
> +using NPOI.Util;
Зачем NPOI используется в доменной модели?

2023-06-19 10:59 UTC, Gankov commented on Workwear/Dialogs/Stock/IncomeDocItemsView.cs
> +				.AddColumn ("Наименование").Resizable().AddTextRenderer (e => e.ItemName).WrapWidth(700)
Зачем? Здесь должны быть номенклатура. Пользователь должен иметь возможность выбрать номенклатуру. Ты же на склад не оприходуешь никак приход без номенклатуры.
Ну или должны быть какая то приписка, номенклатура не выбрана. Чтобы было понятно что пользователь не выбрав номенклатуру не сможет сохранить документ. Тут конечно нужно подумать, какой вариант понятнее будет.

2023-06-19 10:59 UTC, Gankov commented on Workwear/Dialogs/Stock/IncomeDocDlg.cs
> +	public partial class  IncomeDocDlg : EntityDialogBase<Income>
Зачем здесь добавлен лишний пробел?

2023-06-19 10:59 UTC, Gankov commented on Workwear/Dialogs/Stock/IncomeDocItemsView.cs
> -					                                  && incomeDoc.Operation == IncomeOperations.Enter)
Здесь ты по идеи еще и активируешь это поле для возврата с подразделения. Но думаю, тут должна быть другая логика. Думаю, тут надо проверять что в операции выдачи сотруднику размер не указан. Если не указан, а номенклатура с размером, то его необходимо задать. А не давать возможность менять размер во всех случаях, даже если мы возвращаем от сотрудника нормально выданное.

2023-06-20 14:04 UTC, Gankov approved these changes

2023-06-21 06:52 UTC, Gankov approved these changes

2023-06-21 08:44 UTC, Gankov approved these changes

2023-06-21 08:44 UTC, merged