Добавил отчёт по обеспечености
QualitySolution/Workwear pull request #376
Opened 2023-11-21 14:48 UTC by SpaceTranquility

2023-11-21 14:49 UTC, SpaceTranquility commented
![image](https://github.com/QualitySolution/Workwear/assets/47983361/f0477789-a310-45c6-842a-bd9435dc37f3)
![image](https://github.com/QualitySolution/Workwear/assets/47983361/d78b4726-e5c1-4506-911e-b1ab28b499f8)

2023-11-22 06:38 UTC, Gankov requested changes

2023-11-22 06:38 UTC, Gankov commented on Workwear/changes.txt
> +* В справку по размерам добавленаотключаемая группировка по подразделениям.
Напиши правильно, в поразмерный список и там опечатка.

2023-11-22 07:39 UTC, SpaceTranquility commented on Workwear/ReportParameters/ViewModels/ChoiceProtectionToolsViewModel.cs
> +			selectAllState = !selectAllState;
Поменяю на 2 кнопки

2023-11-22 07:39 UTC, SpaceTranquility commented on Workwear/ReportParameters/ViewModels/ChoiseSubdivisionViewModel.cs
> +		public ChoiceSubdivisionViewModel(IUnitOfWorkFactory uowFactory, IUnitOfWork uow)
Забыл удалить.

2023-11-22 09:41 UTC, Gankov submitted a review, later dismissed

2023-11-22 09:45 UTC, Gankov approved these changes

2023-11-22 09:45 UTC, merged