Колонка Номер ведомости в складских движениях
QualitySolution/Workwear pull request #378
Opened 2023-11-29 11:16 UTC by SpaceTranquility

2023-11-29 11:34 UTC, Gankov requested changes

2023-11-29 11:34 UTC, Gankov commented on Workwear/Journal/ViewModels/Stock/StockMovementsJournalViewModel.cs
> +					.Select(() => incomeItemAlias).WithAlias(() => resultAlias.IncomeItemId)
Тебе не кажется что ты в этой строке удалил Id

2023-12-01 08:59 UTC, YariLAN commented on Workwear/Journal/ViewModels/Stock/StockMovementsJournalViewModel.cs
> +					.Select(() => incomeItemAlias).WithAlias(() => resultAlias.IncomeItemId)
Исправил

2023-12-01 09:07 UTC, Gankov approved these changes

2023-12-01 09:11 UTC, Gankov approved these changes

2023-12-01 09:12 UTC, merged