Проверка на редактирование документа постомата
QualitySolution/Workwear pull request #397
Opened 2023-12-12 14:00 UTC by YariLAN

2023-12-14 14:25 UTC, Gankov requested changes

2023-12-14 14:25 UTC, Gankov commented on Workwear/Workwear.csproj
Зачем это менять. Это может привисти к проблемам. Можешь откатить этот файл?

2023-12-15 10:45 UTC, YariLAN commented on Workwear/Workwear.csproj
+

2023-12-17 13:14 UTC, Gankov approved these changes

2023-12-17 13:18 UTC, Gankov approved these changes

2023-12-17 13:19 UTC, merged