Обновляю штрихкод при переключении
QualitySolution/Workwear pull request #498
Opened 2024-06-27 15:48 UTC by SpaceTranquility

2024-06-28 05:55 UTC, Gankov requested changes

2024-06-28 05:55 UTC, Gankov commented on Workwear/ViewModels/Operations/ManualEmployeeIssueOperationsViewModel.cs
> +				OnPropertyChanged(nameof(BarcodesColor));
Не считаю что так правильно. Это нарушает логику. Ведь при запросе текста цвет не меняется, почему это теперь связано с запросом текста не ясно.

2024-07-04 11:48 UTC, SpaceTranquility commented on Workwear/ViewModels/Operations/ManualEmployeeIssueOperationsViewModel.cs
> +				OnPropertyChanged(nameof(BarcodesColor));
Моя логика в том, что цвет - это свойство текста.

2024-07-10 06:40 UTC, Gankov approved these changes
Хуйсним, работает и ладно. Но логика сломана.

2024-07-10 06:41 UTC, merged