Исправила в карточке сотрудника на оборотной стороне подпись и акт списания
QualitySolution/Workwear pull request #541
Opened 2024-10-01 14:30 UTC by Katetim32

Исправила условия для проставления подписи и документов списания/возврата, учла ручное изменение номера списания/возврата.

2024-10-02 07:02 UTC, Gankov requested changes
Ваня объяснит

2024-10-02 13:22 UTC, SpaceTranquility commented on Workwear/Reports/Employee/PersonalCardPageNew2.rdl
>                  stock_income_detail.stock_income_id AS return_doc_id
Тут пропущена запятая, запрос упадёт

2024-10-02 13:22 UTC, SpaceTranquility commented on Workwear/Reports/Employee/PersonalCardPageNew2.rdl
> +                         IF(returned.writeoff_doc_id IS NOT NULL,  GROUP_CONCAT(
Нужно ещё доработать номера документов через GROUP_CONCAT, как с датами, т.к. на одну выдачу, может быть несколько возвратов. Сделал такую ситуацию на сотруднике 1449 в specposhiv_vodokanal23_2024_09_20
Так же на списание

2024-10-03 08:40 UTC, SpaceTranquility approved these changes

2024-10-03 15:24 UTC, Gankov requested changes

2024-10-03 15:24 UTC, Gankov commented on Workwear/Reports/Employee/PersonalCardPageNew2.rdl
> +                      <Value>Акт списания (номер)</Value>
А почему вы решили исправить официальную форму? https://normativ.kontur.ru/document?moduleId=1&documentId=410891#h204

2024-10-04 08:25 UTC, Gankov approved these changes

2024-10-04 08:25 UTC, merged